### ISSUE TITLE
release error code 12

### ISSUE THREAD

**Issue by dbrova15** [myood/godot-ci-android-export#12]
Hello. I use gitlab-ci for compilation.
The debug version builds without problems, but the release version gets an error.
ERROR: _fs_changed: Failed to export project with error code 12 for "Android Release Armeabi-v7a" preset.
    At: editor / editor_node.cpp: 638.

Using Godot 3.2.2

![изображение](https://user-images.githubusercontent.com/20703983/91935713-01d47700-ecf7-11ea-9fd3-ce698ddd0ec1.png)

**Comment by myood** [comment]
Are you sure the release keystore is properly set and you use valid password?

**Comment by myood** [comment]
Closing - no reply from the author

**Comment by myood** [comment]
also see sample gitlab project in README.md
