### ISSUE TITLE
Trying to get debug build ci running

### ISSUE THREAD

**Issue by peterge1998** [myood/godot-ci-android-export#15]
[.gitlab-ci.yml](https://gitlab.com/peterge/combined/-/blob/main/.gitlab-ci.yml)

[export_presets.cfg](https://gitlab.com/peterge/combined/-/blob/main/export_presets.cfg)

I am trying to produce a debug build. Your ci template sounds very promising, but i cant get it to run. Under variables i have `K8S_SECRET_RELEASE_KEYSTORE_BASE64` with the output of `base64 debug.keystore -w 0`. The manually started ci job fails with:
![image](https://user-images.githubusercontent.com/47355238/130440659-bade83a4-608d-4c8e-9f23-90e73849f954.png)

I dont have much experience with this whole stuff, but would like to get it working.
Is there a working example anywhere on gitlab? I cant find one. Maybe link them in README?

**Comment by myood** [comment]
Since you want only debug build, then you don't need K8S_SECRET_* variables.

Comment out in your .gitlab-ci.yml... lines: 31-38, 51-93. (basically anything related to release export)

**Comment by myood** [comment]
... and rename "Android" to "Android Debug" in exports (via Godot GUI or edit export_presets.cfg line 3

**Comment by myood** [comment]
I also added sample project. Seems to work... so you could use it as base.
