### ISSUE TITLE
'/root/android-sdk/platform-tools/adb': No such file or directory

### ISSUE THREAD

**Issue by dbrova15** [myood/godot-ci-android-export#9]
I have a mistake:
![image](https://user-images.githubusercontent.com/20703983/87162558-c311da00-c2ce-11ea-8d9a-1b467c6f458c.png)
I looked at the docker file path and realized that it is not correct. Then I decided to fix the path to .gitlab-ci.yml. But I got the same error.
![image](https://user-images.githubusercontent.com/20703983/87162811-1dab3600-c2cf-11ea-961f-817478163668.png)

**Comment by FeralBytes** [comment]
Same problem.

**Comment by myood** [comment]
Recent changes to master break backward compatibility.
Try using tag with explicit godot version, like godot-3.1.2
There is also a chance, that you pulled image that was broken at the time (It took a few commits to make it work)

Also, provide some more info if you want my help - which Docker tag do you use, which godot version, what your gitlab yaml look like, complete build log.

**edit:** actually it is a bug, fix on the way

**Comment by myood** [comment]
#10 this one should do the trick, can you check? (fix is in sample yaml, so you should update yours accordingly)

**Comment by FeralBytes** [comment]
My current Gitlab Yaml:  https://gitlab.com/FeralBytes/FreecoiL/-/blob/master/.gitlab-ci.yml
image: myood/godot-ci-android-export:godot-3.2.2
Godot Version 3.2.2 Stable
Build Log: https://gitlab.com/FeralBytes/FreecoiL/-/jobs/643097323

I will check the fix tonight, and report back. Thank you.

UPDATE 1: I am going to take one more day to look at the fix. Looks like you changed the paths dramatically.

**Comment by FeralBytes** [comment]
I was still having problems and was going to work through the path to figure it out, but I have a problem with my Android Plugin that is related to trying to get Context and Activity in Godot 3.2.2, because they changed something from 3.2.2-beta4 to stable. So now I have reverted to that image.
